package com.mgiang2015.SpringVideoPlatform.controller;

import java.io.IOException;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.util.FileCopyUtils;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

import com.mgiang2015.SpringVideoPlatform.repository.ChapterRepository;
import com.mgiang2015.SpringVideoPlatform.services.VideoMongodbService;

import jakarta.servlet.http.HttpServletResponse;

import com.mgiang2015.SpringVideoPlatform.exception.ChapterNotFoundException;
import com.mgiang2015.SpringVideoPlatform.model.Chapter;
import com.mgiang2015.SpringVideoPlatform.model.VideoData;

@RestController
public class ChapterController {
    @Autowired
    private ChapterRepository repository;
    @Autowired
    private VideoMongodbService service;

    @GetMapping("/chapters")
    public List<Chapter> all() {
        return repository.findAll();
    }

    @PostMapping("/chapters")
    public Chapter newChapter(@RequestParam("title") String title, @RequestParam("description") String description, @RequestParam("file") MultipartFile file) throws IOException {
        String id = service.addVideo(file);
        
        Chapter newChapter = new Chapter();
        newChapter.setTitle(title);
        newChapter.setDescription(description);
        newChapter.setVideoId(id); // video id generated by mongodb

        return repository.save(newChapter);
    }

    @GetMapping("/chapters/{id}")
    public Chapter one(@PathVariable Long id) {
        return repository.findById(id)
        .orElseThrow(() -> new ChapterNotFoundException(id));
    }
    
    @GetMapping("/chapters/stream/{id}")
    public void streamVideo(@PathVariable Long id, HttpServletResponse response) throws IOException {
        Chapter c = repository.findById(id)
            .orElseThrow(() -> new ChapterNotFoundException(id));
        VideoData data = service.getVideo(c.getVideoId());
        response.addHeader("Content-Type", "video/mp4");
        FileCopyUtils.copy(data.getStream(), response.getOutputStream());
    }

    @PutMapping("/chapters/{id}")
    public Chapter replaceChapter(@RequestBody Chapter newChapter, @PathVariable Long id) {
        return repository.findById(id)
        .map(chapter -> {
            chapter.setTitle(newChapter.getTitle()); // update in SQL
            chapter.setDescription(newChapter.getDescription());
            return repository.save(chapter);
        }).orElseGet(() -> {
            newChapter.setId(id);
            return repository.save(newChapter);
        });
    }

    @DeleteMapping("/chapters/{id}")
    public void deleteChapter(@PathVariable Long id) throws IOException {
        // Delete from mongodb first
        Chapter c = repository.findById(id)
            .orElseThrow(() -> new ChapterNotFoundException(id));
        service.deleteVideo(c.getVideoId());

        // Delete from mysql
        repository.deleteById(id);
    }

    @DeleteMapping("/chapters/all")
    public void deleteAllChapters() {
        List<Chapter> allChapters = repository.findAll();
        for (Chapter chapter : allChapters) {
            service.deleteVideo(chapter.getVideoId());
            repository.deleteById(chapter.getId());
        }
    }
}
